//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocabularyEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int HistoryId { get; set; }
        public int StagedId { get; set; }
        public bool Pass { get; set; }
        public string IncreasedTo { get; set; }
        public System.DateTime At { get; set; }
        public int WordId { get; set; }
        public int UserKey { get; set; }
    
        public virtual StagedWord StagedWord { get; set; }
        public virtual User User { get; set; }
        public virtual Word Word { get; set; }
    }
}
